CREATE TABLE public.geo_assets (id text PRIMARY KEY, topo jsonb NOT NULL, source text, license text, updated_at timestamptz DEFAULT now());
CREATE TABLE public.india_states (id text PRIMARY KEY, name text NOT NULL, name_hi text, name_mr text, population bigint, area_km2 real, lat double precision, lon double precision);
CREATE TABLE public.india_districts (id text PRIMARY KEY, state_id text NOT NULL REFERENCES public.india_states(id), name text NOT NULL, census_code text, lat double precision, lon double precision, population integer, area_km2 real);
CREATE INDEX india_districts_state_idx ON public.india_districts (state_id);
CREATE TABLE public.india_district_weather (district_id text PRIMARY KEY REFERENCES public.india_districts(id) ON DELETE CASCADE, as_of date, temp_mean_7d real, temp_max_7d real, temp_min_7d real, humidity_7d real, rain_7d_mm real, rain_14d_mm real, rain_next7d_mm real, temp_next7d real, wind_speed_max real, wind_dir_deg real, cloud_cover real, aedes_suitability real, anopheles_suitability real, updated_at timestamptz DEFAULT now());
CREATE TABLE public.country_reported (iso3 text NOT NULL, disease_id text NOT NULL, year int NOT NULL, indicator text NOT NULL, value real, source text, PRIMARY KEY (iso3, disease_id, year, indicator));
CREATE TABLE public.india_district_history (district_name text NOT NULL, week_start date NOT NULL, cases int, deaths int, PRIMARY KEY (district_name, week_start));
ALTER TABLE public.admin1_burden ADD COLUMN deaths real, ADD COLUMN confirmed real, ADD COLUMN tested real, ADD COLUMN pf real;
GRANT SELECT ON public.geo_assets, public.india_states, public.india_districts, public.india_district_weather, public.country_reported, public.india_district_history TO anon, authenticated;
GRANT ALL ON public.geo_assets, public.india_states, public.india_districts, public.india_district_weather, public.country_reported, public.india_district_history TO service_role;
ALTER TABLE public.geo_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.india_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.india_districts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.india_district_weather ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.country_reported ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.india_district_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON public.geo_assets FOR SELECT USING (true);
CREATE POLICY "Public read" ON public.india_states FOR SELECT USING (true);
CREATE POLICY "Public read" ON public.india_districts FOR SELECT USING (true);
CREATE POLICY "Public read" ON public.india_district_weather FOR SELECT USING (true);
CREATE POLICY "Public read" ON public.country_reported FOR SELECT USING (true);
CREATE POLICY "Public read" ON public.india_district_history FOR SELECT USING (true);
INSERT INTO public.diseases (id, name, vector) VALUES ('cholera', 'Cholera', 'none (water-borne)') ON CONFLICT (id) DO NOTHING;