/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicRefreshIctsRouteImport } from './routes/api/public/refresh-icts'
import { Route as ApiPublicRefreshIndiaWeatherRouteImport } from './routes/api/public/refresh-india-weather'
import { Route as ApiPublicRefreshWeatherRouteImport } from './routes/api/public/refresh-weather'
import { Route as ApiPublicRefreshWhoRouteImport } from './routes/api/public/refresh-who'
import { Route as ApiPublicRefreshWorldWeatherRouteImport } from './routes/api/public/refresh-world-weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshIctsRoute = ApiPublicRefreshIctsRouteImport.update({
  id: '/api/public/refresh-icts',
  path: '/api/public/refresh-icts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshIndiaWeatherRoute =
  ApiPublicRefreshIndiaWeatherRouteImport.update({
    id: '/api/public/refresh-india-weather',
    path: '/api/public/refresh-india-weather',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRefreshWeatherRoute = ApiPublicRefreshWeatherRouteImport.update({
  id: '/api/public/refresh-weather',
  path: '/api/public/refresh-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshWhoRoute = ApiPublicRefreshWhoRouteImport.update({
  id: '/api/public/refresh-who',
  path: '/api/public/refresh-who',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshWorldWeatherRoute =
  ApiPublicRefreshWorldWeatherRouteImport.update({
    id: '/api/public/refresh-world-weather',
    path: '/api/public/refresh-world-weather',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/map': typeof MapRoute
  '/replay': typeof ReplayRoute
  '/scenarios': typeof ScenariosRoute
  '/trust': typeof TrustRoute
  '/world': typeof WorldRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/refresh-icts': typeof ApiPublicRefreshIctsRoute
  '/api/public/refresh-india-weather': typeof ApiPublicRefreshIndiaWeatherRoute
  '/api/public/refresh-weather': typeof ApiPublicRefreshWeatherRoute
  '/api/public/refresh-who': typeof ApiPublicRefreshWhoRoute
  '/api/public/refresh-world-weather': typeof ApiPublicRefreshWorldWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/map': typeof MapRoute
  '/replay': typeof ReplayRoute
  '/scenarios': typeof ScenariosRoute
  '/trust': typeof TrustRoute
  '/world': typeof WorldRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/refresh-icts': typeof ApiPublicRefreshIctsRoute
  '/api/public/refresh-india-weather': typeof ApiPublicRefreshIndiaWeatherRoute
  '/api/public/refresh-weather': typeof ApiPublicRefreshWeatherRoute
  '/api/public/refresh-who': typeof ApiPublicRefreshWhoRoute
  '/api/public/refresh-world-weather': typeof ApiPublicRefreshWorldWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/map': typeof MapRoute
  '/replay': typeof ReplayRoute
  '/scenarios': typeof ScenariosRoute
  '/trust': typeof TrustRoute
  '/world': typeof WorldRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/refresh-icts': typeof ApiPublicRefreshIctsRoute
  '/api/public/refresh-india-weather': typeof ApiPublicRefreshIndiaWeatherRoute
  '/api/public/refresh-weather': typeof ApiPublicRefreshWeatherRoute
  '/api/public/refresh-who': typeof ApiPublicRefreshWhoRoute
  '/api/public/refresh-world-weather': typeof ApiPublicRefreshWorldWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/map'
    | '/replay'
    | '/scenarios'
    | '/trust'
    | '/world'
    | '/api/public/ingest'
    | '/api/public/refresh-icts'
    | '/api/public/refresh-india-weather'
    | '/api/public/refresh-weather'
    | '/api/public/refresh-who'
    | '/api/public/refresh-world-weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/map'
    | '/replay'
    | '/scenarios'
    | '/trust'
    | '/world'
    | '/api/public/ingest'
    | '/api/public/refresh-icts'
    | '/api/public/refresh-india-weather'
    | '/api/public/refresh-weather'
    | '/api/public/refresh-who'
    | '/api/public/refresh-world-weather'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/map'
    | '/replay'
    | '/scenarios'
    | '/trust'
    | '/world'
    | '/api/public/ingest'
    | '/api/public/refresh-icts'
    | '/api/public/refresh-india-weather'
    | '/api/public/refresh-weather'
    | '/api/public/refresh-who'
    | '/api/public/refresh-world-weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  MapRoute: typeof MapRoute
  ReplayRoute: typeof ReplayRoute
  ScenariosRoute: typeof ScenariosRoute
  TrustRoute: typeof TrustRoute
  WorldRoute: typeof WorldRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicRefreshIctsRoute: typeof ApiPublicRefreshIctsRoute
  ApiPublicRefreshIndiaWeatherRoute: typeof ApiPublicRefreshIndiaWeatherRoute
  ApiPublicRefreshWeatherRoute: typeof ApiPublicRefreshWeatherRoute
  ApiPublicRefreshWhoRoute: typeof ApiPublicRefreshWhoRoute
  ApiPublicRefreshWorldWeatherRoute: typeof ApiPublicRefreshWorldWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-icts': {
      id: '/api/public/refresh-icts'
      path: '/api/public/refresh-icts'
      fullPath: '/api/public/refresh-icts'
      preLoaderRoute: typeof ApiPublicRefreshIctsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-india-weather': {
      id: '/api/public/refresh-india-weather'
      path: '/api/public/refresh-india-weather'
      fullPath: '/api/public/refresh-india-weather'
      preLoaderRoute: typeof ApiPublicRefreshIndiaWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-weather': {
      id: '/api/public/refresh-weather'
      path: '/api/public/refresh-weather'
      fullPath: '/api/public/refresh-weather'
      preLoaderRoute: typeof ApiPublicRefreshWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-who': {
      id: '/api/public/refresh-who'
      path: '/api/public/refresh-who'
      fullPath: '/api/public/refresh-who'
      preLoaderRoute: typeof ApiPublicRefreshWhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-world-weather': {
      id: '/api/public/refresh-world-weather'
      path: '/api/public/refresh-world-weather'
      fullPath: '/api/public/refresh-world-weather'
      preLoaderRoute: typeof ApiPublicRefreshWorldWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  MapRoute: MapRoute,
  ReplayRoute: ReplayRoute,
  ScenariosRoute: ScenariosRoute,
  TrustRoute: TrustRoute,
  WorldRoute: WorldRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicRefreshIctsRoute: ApiPublicRefreshIctsRoute,
  ApiPublicRefreshIndiaWeatherRoute: ApiPublicRefreshIndiaWeatherRoute,
  ApiPublicRefreshWeatherRoute: ApiPublicRefreshWeatherRoute,
  ApiPublicRefreshWhoRoute: ApiPublicRefreshWhoRoute,
  ApiPublicRefreshWorldWeatherRoute: ApiPublicRefreshWorldWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
